LU_SRC = \
	$(POLYBENCH_ROOT)/$(LU_ROOT)/lu.c \
	$(POLYBENCH_ROOT)/utilities/polybench.c


$(POLYBENCH_BUILD)/$(LU_ROOT)/%.bin: $(POLYBENCH_BUILD)/$(LU_ROOT)
	@$(VERBOSE) $(COMPILER) $(CPPFLAGS) $(LU_SRC) -o $@ $(EXTRA_FLAGS)

$(POLYBENCH_BUILD)/$(LU_ROOT):
	@mkdir -p $@
