name: Tests

on:
  pull_request:
    branches: [ master ]

env:
  JLM_ROOT_DIR: /tmp/jlm

jobs:
  polybench:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.title, '[DisableCI]') == false
    steps:
    - uses: actions/checkout@v4
    - name: "Install packages"
      uses: ./.github/actions/InstallPackages
      with:
        llvm-version: 18

    - name: "Clone jlm"
      run: git clone https://github.com/phate/jlm.git $JLM_ROOT_DIR
      shell: bash

    - name: "configure and build jlm"
      run: |
        cd $JLM_ROOT_DIR && \
        ./configure.sh --target release --enable-asserts CXX=clang++ && \
        make -j `nproc` -O all
      shell: bash

    - name: "Add executables to PATH"
      run: |
        echo "${JLM_ROOT_DIR}/build" >> $GITHUB_PATH
      shell: bash

    - name: "Run the polybench suite"
      run: make -j `nproc` -O check
      shell: bash
